# Generated by Django 4.2.16 on 2024-11-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_producto_f_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneral',
            name='lab_dire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='laboratorio.laboratorio'),
        ),
    ]
