# Generated by Django 5.1.3 on 2024-11-30 12:55

import laboratorio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_alter_directorgeneral_lab_dire'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='alias_lab',
            field=models.CharField(default=2024, max_length=255, verbose_name='alias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='f_expiracion',
            field=models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044'), (2045, '2045'), (2046, '2046'), (2047, '2047'), (2048, '2048'), (2049, '2049'), (2050, '2050')], default=laboratorio.models.anio_actual, verbose_name='F Expiración'),
        ),
    ]
